# English team names -> Arabic (for DB migration)

TEAM_EN_TO_AR: dict[str, str] = {
    "Mexico": "المكسيك",
    "South Africa": "جنوب أفريقيا",
    "South Korea": "كوريا الجنوبية",
    "Czechia": "التشيك",
    "Canada": "كندا",
    "Bosnia and Herzegovina": "البوسنة والهرسك",
    "USA": "الولايات المتحدة",
    "Paraguay": "باراغواي",
    "Haiti": "هايتي",
    "Scotland": "اسكتلندا",
    "Australia": "أستراليا",
    "Turkiye": "تركيا",
    "Brazil": "البرازيل",
    "Morocco": "المغرب",
    "Qatar": "قطر",
    "Switzerland": "سويسرا",
    "Ivory Coast": "ساحل العاج",
    "Ecuador": "الإكوادور",
    "Germany": "ألمانيا",
    "Curacao": "كوراساو",
    "Netherlands": "هولندا",
    "Japan": "اليابان",
    "Sweden": "السويد",
    "Tunisia": "تونس",
    "Saudi Arabia": "السعودية",
    "Uruguay": "الأوروغواي",
    "Spain": "إسبانيا",
    "Cape Verde": "الرأس الأخضر",
    "Iran": "إيران",
    "New Zealand": "نيوزيلندا",
    "Belgium": "بلجيكا",
    "Egypt": "مصر",
    "France": "فرنسا",
    "Senegal": "السنغال",
    "Iraq": "العراق",
    "Norway": "النرويج",
    "Argentina": "الأرجنتين",
    "Algeria": "الجزائر",
    "Austria": "النمسا",
    "Jordan": "الأردن",
    "Ghana": "غانا",
    "Panama": "بنما",
    "England": "إنجلترا",
    "Croatia": "كرواتيا",
    "Portugal": "البرتغال",
    "DR Congo": "الكونغو الديمقراطية",
    "Uzbekistan": "أوزبكستان",
    "Colombia": "كولومبيا",
    # Knockout placeholders
    "Group A 2nd": "ثاني المجموعة أ",
    "Group B 2nd": "ثاني المجموعة ب",
    "Group C 2nd": "ثاني المجموعة ج",
    "Group D 2nd": "ثاني المجموعة د",
    "Group E 1st": "أول المجموعة هـ",
    "Group E 2nd": "ثاني المجموعة هـ",
    "Group F 1st": "أول المجموعة و",
    "Group F 2nd": "ثاني المجموعة و",
    "Group C 1st": "أول المجموعة ج",
    "Group A 1st": "أول المجموعة أ",
    "Group I 1st": "أول المجموعة ط",
    "Group I 2nd": "ثاني المجموعة ط",
    "Group L 1st": "أول المجموعة ل",
    "Group L 2nd": "ثاني المجموعة ل",
    "Group D 1st": "أول المجموعة د",
    "Group G 1st": "أول المجموعة ز",
    "Group G 2nd": "ثاني المجموعة ز",
    "Group K 1st": "أول المجموعة ك",
    "Group K 2nd": "ثاني المجموعة ك",
    "Group H 1st": "أول المجموعة ح",
    "Group H 2nd": "ثاني المجموعة ح",
    "Group B 1st": "أول المجموعة ب",
    "Group J 1st": "أول المجموعة ي",
    "Group J 2nd": "ثاني المجموعة ي",
    "3rd Group A/B/C/D/F": "ثالث (أ/ب/ج/د/و)",
    "3rd Group C/D/F/G/H": "ثالث (ج/د/و/ز/ح)",
    "3rd Group C/E/F/H/I": "ثالث (ج/هـ/و/ح/ط)",
    "3rd Group E/H/I/J/K": "ثالث (هـ/ح/ط/ي/ك)",
    "3rd Group B/E/F/I/J": "ثالث (ب/هـ/و/ط/ي)",
    "3rd Group A/E/H/I/J": "ثالث (أ/هـ/ح/ط/ي)",
    "3rd Group E/F/G/I/J": "ثالث (هـ/و/ز/ط/ي)",
    "3rd Group D/E/I/J/L": "ثالث (د/هـ/ط/ي/ل)",
    "Winner M73": "فائز م٧٣",
    "Winner M74": "فائز م٧٤",
    "Winner M75": "فائز م٧٥",
    "Winner M76": "فائز م٧٦",
    "Winner M77": "فائز م٧٧",
    "Winner M78": "فائز م٧٨",
    "Winner M79": "فائز م٧٩",
    "Winner M80": "فائز م٨٠",
    "Winner M81": "فائز م٨١",
    "Winner M82": "فائز م٨٢",
    "Winner M83": "فائز م٨٣",
    "Winner M84": "فائز م٨٤",
    "Winner M85": "فائز م٨٥",
    "Winner M86": "فائز م٨٦",
    "Winner M87": "فائز م٨٧",
    "Winner M88": "فائز م٨٨",
    "Winner M89": "فائز م٨٩",
    "Winner M90": "فائز م٩٠",
    "Winner M91": "فائز م٩١",
    "Winner M92": "فائز م٩٢",
    "Winner M93": "فائز م٩٣",
    "Winner M94": "فائز م٩٤",
    "Winner M95": "فائز م٩٥",
    "Winner M96": "فائز م٩٦",
    "Winner M97": "فائز م٩٧",
    "Winner M98": "فائز م٩٨",
    "Winner M99": "فائز م٩٩",
    "Winner M100": "فائز م١٠٠",
    "Winner M101": "فائز م١٠١",
    "Winner M102": "فائز م١٠٢",
    "Runner-up M101": "وصيف م١٠١",
    "Runner-up M102": "وصيف م١٠٢",
}

GROUP_EN_TO_AR: dict[str, str] = {
    "Group A": "المجموعة أ",
    "Group B": "المجموعة ب",
    "Group C": "المجموعة ج",
    "Group D": "المجموعة د",
    "Group E": "المجموعة هـ",
    "Group F": "المجموعة و",
    "Group G": "المجموعة ز",
    "Group H": "المجموعة ح",
    "Group I": "المجموعة ط",
    "Group J": "المجموعة ي",
    "Group K": "المجموعة ك",
    "Group L": "المجموعة ل",
    "Round of 32": "دور الـ32",
    "Round of 16": "دور الـ16",
    "Quarter-final": "ربع النهائي",
    "Semi-final": "نصف النهائي",
    "3rd place": "مباراة المركز الثالث",
    "Final": "النهائي",
}
